keys:
  - age17a9l2nrwmv7kx2zywte97h9uvf206r82ta8h747vydaayvhkheqsycwx36
creation_rules:
  - path_regex: hosts/.*/secrets.yaml
    key_groups:
      - age:
          - age17a9l2nrwmv7kx2zywte97h9uvf206r82ta8h747vydaayvhkheqsycwx36
  - path_regex: hosts/.*.yaml
    key_groups:
      - age:
          - age17a9l2nrwmv7kx2zywte97h9uvf206r82ta8h747vydaayvhkheqsycwx36
