keys:
  - age1yu88qctep4le04aadz70gf8gcjkxh78z3mdtnh4s5wyg9z7edskqz3h00n
creation_rules:
  - path_regex: hosts/.*/secrets.yaml
    key_groups:
      - age:
          - age1yu88qctep4le04aadz70gf8gcjkxh78z3mdtnh4s5wyg9z7edskqz3h00n
  - path_regex: hosts/.*.yaml
    key_groups:
      - age:
          - age1yu88qctep4le04aadz70gf8gcjkxh78z3mdtnh4s5wyg9z7edskqz3h00n
