keys:
  - age1duxq5dnyhtxxp0yhsfqeup40ug7a4yp70vc8jgkytaqrq95mxq5qnmefdz
creation_rules:
  - path_regex: hosts/*/secrets.yaml
    key_groups:
      - age:
          - age1duxq5dnyhtxxp0yhsfqeup40ug7a4yp70vc8jgkytaqrq95mxq5qnmefdz
  - path_regex: hosts/secrets.yaml
    key_groups:
      - age:
          - age1duxq5dnyhtxxp0yhsfqeup40ug7a4yp70vc8jgkytaqrq95mxq5qnmefdz
