keys:
  - age15x7qjfqjrqv2zrah40jywjf8txv65msvx9gfx66vmjehfx8rvs4qx8tj4h
creation_rules:
  - path_regex: hosts/.*/.*.yaml
    key_groups:
      - age:
          - age15x7qjfqjrqv2zrah40jywjf8txv65msvx9gfx66vmjehfx8rvs4qx8tj4h
  - path_regex: hosts/.*.yaml
    key_groups:
      - age:
          - age15x7qjfqjrqv2zrah40jywjf8txv65msvx9gfx66vmjehfx8rvs4qx8tj4h
