keys:
  - &main age1zjmhl9xc3jrxnwxpe6hhwp4sf5c6gzs7qjk6y4tgdr9ufvdwayhs79afen
creation_rules:
  - path_regex: secrets/common.yaml
    key_groups:
      - age:
          - *main
  - path_regex: secrets/aaron.yaml
    key_groups:
      - age:
          - *main
