name: Build Nixos ISO
on: workflow_dispatch
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix build ".#nixosConfigurations.iso.config.system.build.isoImage"
          ls ./result
          ls ./result/iso
          ISO_PATH=$(readlink ./result)/iso/nixos.iso
          echo "iso_path=$ISO_PATH" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: nixos.iso
          path: ${{ env.iso_path }}
