name: Build Nixos ISO
on: workflow_dispatch
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix build ".#nixosConfigurations.iso.config.system.build.isoImage" --out-link ./result/iso
      - uses: actions/upload-artifact@v4
        with:
          name: nixos.iso
          path: ./result/iso/nixos.iso
