name: Build Nixos ISO
on: workflow_dispatch
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build ISO image
        run: |
          # Build the ISO image
          nix build ".#nixosConfigurations.iso.config.system.build.isoImage"
          
          # Find the actual ISO path using find, independent of specific path structure
          ISO_PATH=$(find $(readlink -f result) -name "*.iso" | head -n 1)
          
          if [ -z "$ISO_PATH" ]; then
            echo "ERROR: No ISO file found in build output"
            find $(readlink -f result) -type f | grep -v '\.drv$' # Show available files for debugging
            exit 1
          fi
          
          echo "Found ISO at: $ISO_PATH"
          echo "iso_path=$ISO_PATH" >> $GITHUB_ENV
          
          # Copy the ISO to a predictable location
          cp "$ISO_PATH" ./nixos.iso
          
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos.iso
          path: ./nixos.iso
          if-no-files-found: error  # Fail explicitly if no file found
