name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * *' # runs daily at 00:00
jobs:
  lockfile:
    runs-on: ubuntu-latest
    environment: update
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ secrets.NIX_FLAKE_UPDATE_TOKEN }}
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated
            nix
