name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs every Sunday at 00:00
jobs:
  lockfile:
    runs-on: ubuntu-latest
    environment: update
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update flake.lock
        id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.NIX_FLAKE_UPDATE_TOKEN }}
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated
            nix
          git-author-name: "Nix flake updater"
          git-author-email: "github-actions[bot]@users.noreply.github.com"
          git-committer-name: "Nix flake updater"
          git-committer-email: "github-actions[bot]@users.noreply.github.com"
